In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
import bs4

print(f"NumPy Version --> {np.__version__}")
print(f"Pandas Version --> {pd.__version__}")
print(f"Python requests Version --> {requests.__version__}")
print(f"Beautiful Soup Version --> {bs4.__version__}")

print("\nAll libraries imported successfully")

NumPy Version --> 2.4.6
Pandas Version --> 3.0.3
Python requests Version --> 2.34.2
Beautiful Soup Version --> 4.15.0

All libraries imported successfully

In [1]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

data = pd.read_csv("../raw-dataset/Airbnb_Open_Data.csv")
print(f"First 5 rows of the dataset: \n{data.head(5)}")

NameError: name 'pd' is not defined

In [3]:
print(f"Shape: {data.shape}")
print(f"\nColumns: {data.columns}")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

display(data.sample(3))

Shape: (102599, 26)

Columns: Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
71530,40507355,Large 1 Bdrm for 5; close to Roberta's / Morgan L,55408555802,verified,Peter,Brooklyn,Bushwick,40.70222,-73.93294,United States,US,False,strict,Entire home/apt,2015.0,$913,$183,3.0,109.0,7/1/2019,2.50,3.0,2.0,191.0,NaN,NaN
27962,16444749,Manhattan Luxury & Cozy Studio,71295668242,verified,Arianne,Manhattan,Financial District,40.70407,-74.00885,United States,US,True,moderate,Entire home/apt,2015.0,$849,$170,1.0,13.0,7/7/2019,0.67,3.0,1.0,1.0,This is a fragrance free property. I have fra...,NaN
6861,4790666,Boutique Retreat,3541128874,unconfirmed,Jacqueline,Bronx,Mount Hope,40.85062,-73.90251,United States,US,True,flexible,Private room,2017.0,"$1,046",$209,14.0,5.0,6/17/2017,0.13,5.0,1.0,36.0,No pets and no smoking (including outside near...,NaN

In [4]:
new_columns = []
for i in data.columns:
    new_columns.append(i.lower().capitalize())

data.columns = new_columns
print(data.columns)

Index(['Id', 'Name', 'Host id', 'Host_identity_verified', 'Host name',
       'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long', 'Country',
       'Country code', 'Instant_bookable', 'Cancellation_policy', 'Room type',
       'Construction year', 'Price', 'Service fee', 'Minimum nights',
       'Number of reviews', 'Last review', 'Reviews per month',
       'Review rate number', 'Calculated host listings count',
       'Availability 365', 'House_rules', 'License'],
      dtype='str')

In [5]:
columns_to_drop = ['Id', 'Reviews per month', 'Review rate number',
       'Calculated host listings count', 'Availability 365', 'House_rules', 'License']

data.drop(columns=columns_to_drop, inplace=True)
print(data.shape)

(102599, 19)

In [6]:
data.drop_duplicates(inplace=True)
print(int(data.duplicated().sum()))

0

In [7]:
data.dropna(inplace=True)
print(data.isna().sum())
print(data.shape)

Name                      0
Host id                   0
Host_identity_verified    0
Host name                 0
Neighbourhood group       0
Neighbourhood             0
Lat                       0
Long                      0
Country                   0
Country code              0
Instant_bookable          0
Cancellation_policy       0
Room type                 0
Construction year         0
Price                     0
Service fee               0
Minimum nights            0
Number of reviews         0
Last review               0
dtype: int64
(83969, 19)

In [13]:
cols = ["Host_identity_verified",  "Cancellation_policy"]

for col in cols:
    data[col] = data[col].astype(str).str.upper()


display(data[cols].head(10))

  Host_identity_verified Cancellation_policy
0            UNCONFIRMED              STRICT
1               VERIFIED            MODERATE
2               VERIFIED            MODERATE
3               VERIFIED            FLEXIBLE
4            UNCONFIRMED            MODERATE
5               VERIFIED              STRICT
6            UNCONFIRMED              STRICT
7               VERIFIED            FLEXIBLE
8               VERIFIED            FLEXIBLE
9               VERIFIED            MODERATE

In [14]:
data.reset_index(inplace=True)
display(data.head(10))

,index,Original index,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,STRICT,Private room,2020.0,966.0,193.0,10.0,9.0,10-19-2021
1,1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,MODERATE,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,5-21-2022
2,2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,MODERATE,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,11-19-2018
3,3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,FLEXIBLE,Entire home/apt,2013.0,577.0,115.0,3.0,74.0,6-22-2019
4,4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,MODERATE,Private room,2009.0,1060.0,212.0,45.0,49.0,10-5-2017
5,5,8,Large Furnished Room Near B'way,79384379533,VERIFIED,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,STRICT,Private room,2005.0,1018.0,204.0,2.0,430.0,6-24-2019
6,6,9,Cozy Clean Guest Room - Family Apt,75527839483,UNCONFIRMED,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,STRICT,Private room,2015.0,291.0,58.0,2.0,118.0,7-21-2017
7,7,10,Cute & Cozy Lower East Side 1 bdrm,1280143094,VERIFIED,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,US,False,FLEXIBLE,Entire home/apt,2004.0,319.0,64.0,1.0,160.0,6-9-2019
8,8,11,Beautiful 1br on Upper West Side,18824631834,VERIFIED,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,US,True,FLEXIBLE,Entire home/apt,2008.0,606.0,121.0,5.0,53.0,6-22-2019
9,9,13,"Lovely Room 1, Garden, Best Area, Legal rental",26802410424,VERIFIED,Darcy,brookln,South Slope,40.66829,-73.98779,United States,US,True,MODERATE,Private room,2010.0,580.0,116.0,4.0,167.0,6-24-2019

In [15]:
data["Price"] = data["Price"].astype(str).str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip()
data["Service fee"] = data["Service fee"].astype(str).str.replace("$", "", regex=False).str.strip()

data["Price"] = data["Price"].astype(float)
data["Service fee"] = data["Service fee"].astype(float)

display(data[["Price", "Service fee"]].head())

    Price  Service fee
0   966.0        193.0
1   142.0         28.0
2   204.0         41.0
3   577.0        115.0
4  1060.0        212.0

In [16]:
data["Last review"] = data["Last review"].astype(str).str.replace("/", "-", regex=False)
data = data.rename(columns={"index": "Original index"})
display(data.head(10))

,Original index,Original index,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,STRICT,Private room,2020.0,966.0,193.0,10.0,9.0,10-19-2021
1,1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,MODERATE,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,5-21-2022
2,2,4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,MODERATE,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,11-19-2018
3,3,5,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,FLEXIBLE,Entire home/apt,2013.0,577.0,115.0,3.0,74.0,6-22-2019
4,4,7,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,MODERATE,Private room,2009.0,1060.0,212.0,45.0,49.0,10-5-2017
5,5,8,Large Furnished Room Near B'way,79384379533,VERIFIED,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,STRICT,Private room,2005.0,1018.0,204.0,2.0,430.0,6-24-2019
6,6,9,Cozy Clean Guest Room - Family Apt,75527839483,UNCONFIRMED,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,STRICT,Private room,2015.0,291.0,58.0,2.0,118.0,7-21-2017
7,7,10,Cute & Cozy Lower East Side 1 bdrm,1280143094,VERIFIED,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,US,False,FLEXIBLE,Entire home/apt,2004.0,319.0,64.0,1.0,160.0,6-9-2019
8,8,11,Beautiful 1br on Upper West Side,18824631834,VERIFIED,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,US,True,FLEXIBLE,Entire home/apt,2008.0,606.0,121.0,5.0,53.0,6-22-2019
9,9,13,"Lovely Room 1, Garden, Best Area, Legal rental",26802410424,VERIFIED,Darcy,brookln,South Slope,40.66829,-73.98779,United States,US,True,MODERATE,Private room,2010.0,580.0,116.0,4.0,167.0,6-24-2019

In [25]:
data.head(10)

,Original index,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,STRICT,Private room,2020.0,966.0,193.0,10.0,9.0,10-19-2021
1,1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,MODERATE,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,5-21-2022
2,2,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,MODERATE,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,11-19-2018
3,3,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,FLEXIBLE,Entire home/apt,2013.0,577.0,115.0,3.0,74.0,6-22-2019
4,4,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,MODERATE,Private room,2009.0,1060.0,212.0,45.0,49.0,10-5-2017
5,5,Large Furnished Room Near B'way,79384379533,VERIFIED,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,STRICT,Private room,2005.0,1018.0,204.0,2.0,430.0,6-24-2019
6,6,Cozy Clean Guest Room - Family Apt,75527839483,UNCONFIRMED,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,STRICT,Private room,2015.0,291.0,58.0,2.0,118.0,7-21-2017
7,7,Cute & Cozy Lower East Side 1 bdrm,1280143094,VERIFIED,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,US,False,FLEXIBLE,Entire home/apt,2004.0,319.0,64.0,1.0,160.0,6-9-2019
8,8,Beautiful 1br on Upper West Side,18824631834,VERIFIED,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,US,True,FLEXIBLE,Entire home/apt,2008.0,606.0,121.0,5.0,53.0,6-22-2019
9,9,"Lovely Room 1, Garden, Best Area, Legal rental",26802410424,VERIFIED,Darcy,brookln,South Slope,40.66829,-73.98779,United States,US,True,MODERATE,Private room,2010.0,580.0,116.0,4.0,167.0,6-24-2019

# Reviewing the Cleaned Dataset

In [26]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 83969 entries, 0 to 83968
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Original index          83969 non-null  int64
 1   Name                    83969 non-null  str
 2   Host id                 83969 non-null  int64
 3   Host_identity_verified  83969 non-null  str
 4   Host name               83969 non-null  str
 5   Neighbourhood group     83969 non-null  str
 6   Neighbourhood           83969 non-null  str
 7   Lat                     83969 non-null  float64
 8   Long                    83969 non-null  float64
 9   Country                 83969 non-null  str
 10  Country code            83969 non-null  str
 11  Instant_bookable        83969 non-null  str
 12  Cancellation_policy     83969 non-null  str
 13  Room type               83969 non-null  str
 14  Construction year       83969 non-null  float64
 15  Price                   83969 non-null  float64
 16  Service fee             83969 non-null  float64
 17  Minimum nights          83969 non-null  float64
 18  Number of reviews       83969 non-null  float64
 19  Last review             83969 non-null  str
dtypes: float64(7), int64(2), str(11)
memory usage: 12.8 MB

In [23]:
data.columns

Index(['Original index', 'Name', 'Host id', 'Host_identity_verified',
       'Host name', 'Neighbourhood group', 'Neighbourhood', 'Lat', 'Long',
       'Country', 'Country code', 'Instant_bookable', 'Cancellation_policy',
       'Room type', 'Construction year', 'Price', 'Service fee',
       'Minimum nights', 'Number of reviews', 'Last review'],
      dtype='str')

In [27]:
len(data.columns)

20

# Exporting Cleaned Dataset as a .csv

In [28]:
data.to_csv("Cleaned_Dataset.csv")