# Importing Packages

In [1]:
import pandas as pd
import numpy as np
import openpyxl

print(f"NumPy Version --> {np.__version__}")
print(f"Pandas Version --> {pd.__version__}")
print(f"openpyxl Version --> {openpyxl.__version__}")

NumPy Version --> 2.4.6
Pandas Version --> 3.0.3
openpyxl Version --> 3.1.5

# Reading the .csv file

In [2]:
data = pd.read_csv("../raw_dataset/zomato.csv")

In [3]:
data.head(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [4]:
data.shape

(51717, 17)

In [5]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  str
 1   address                      51717 non-null  str
 2   name                         51717 non-null  str
 3   online_order                 51717 non-null  str
 4   book_table                   51717 non-null  str
 5   rate                         43942 non-null  str
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  str
 8   location                     51696 non-null  str
 9   rest_type                    51490 non-null  str
 10  dish_liked                   23639 non-null  str
 11  cuisines                     51672 non-null  str
 12  approx_cost(for two people)  51371 non-null  str
 13  reviews_list                 51717 non-null  str
 14  menu_item                    51717 non-null  str
 15  listed_in(type)              51717 non-null  str
 16  listed_in(city)              51717 non-null  str
dtypes: int64(1), str(16)
memory usage: 6.7 MB

In [7]:
data["menu_item"].value_counts()

menu_item
[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 39617
['Butter Chicken Pizza', 'Bombay Veggie Burger', 'Tawa Paneer Burger', 'Oh So Cheesy Burger', 'Barbecue Chicken Burger', 'Peri Peri Chicken Burger', 'BBQ Lamb', 'Cheesy Chicken', 'Crunchy Ferrero', 'Lots of Nuts', 'Kadhai Paneer Pizza', 'Chilli Paneer and Mushroom Pizza', 'Chipotle Veggie Pizza', 'Creamy Cheese Pizza', 'Southern Veggie Korma Pizza', 'Popeye, The Corny Man Pizza', 'Paneer Tikka Pizza', 'Desi Margherita Pizza', 'Roasted Paneer with Mustard Pizza', 'Bangalore Express Pizza', 'Italian Chaska Pizza', 'Mayo and Cheese Pizza', 'Classic Margherita', 'Cajun Hawaiian Pizza', 'Butter Chicken Pizza', 'Lasooni Bhuna Murg Pizza', 'Chilly Chicken Pizza', 'Hot Garlic Chicken Pizza', 'Murg Barbecue Pizza', 'Mediterranean Mutton Keema Pizza', 'Super Green Burger', 'Quinoa Black Bean Burger', 'Bombay Veggie Burger', 'Tawa Paneer Burger', 'Oh So Cheesy Burger', 'Barbecue Chicken Burger', 'Chipotle Lamb Burger', 'Crumb Fried Fish Burger', 'Peri Peri Chicken Burger', 'BBQ Lamb', 'Cheesy Chicken', 'Picnic Chicken Burger', 'Korean Grilled Chicken with Kimchi', 'Kiddy Kat Strawberry', 'Kiddy Kat Chocolate', 'Bubblegum', 'Oreo Shake', 'Caramel Shake', 'Chocolate Shake', 'Strawberry Shake', 'Vanilla Shake', 'Cold Coffee', 'Virgin Mojito', 'Iced Tea', 'Hot Chocolate', 'Cappuccino', 'Latte', 'Espresso Shot', 'Brownie Shake', 'Red Velvet Cheesecake Shake', 'Oreo Cheesecake Shake', 'Salted Caramel Popcorn', 'Coconut Crumble', 'Coffee Crunch', 'Bira', 'Thanda Paan', 'Sticky Toffee Pudding', 'Blueberry Cheesecake', 'Nutella Cheesecake', 'Caramel Custard with Strawberry or Figs', 'Red Velvet Cheesecake', 'Tiramisu', 'Zesty Vanilla and Tipsy Brownie', 'Oreo Explosion', 'Chocolate Almond Crumble', 'Crunchy Ferrero', "Stoner's Chocolate Decadence", 'Brownie Bash', 'Chocolate Lava', 'Dark Chocolate Caramel', 'Chocolate Overload', 'Lots of Nuts', 'Peanut Butter Crunch', 'Nutty Fudgy', 'Lemon Pistachio Biscotti', 'Frutilicious Ice Cream', 'Strawberry Tease Ice Cream', 'Mango Tango Ice Cream', 'Lychee Lovers Ice Cream', 'Monkey Business Ice Cream', 'Apple Crumble Ice Cream', 'Blueberry Bliss Ice Cream']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  11

In [8]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='str')

# Removing Redundant Columns

In [9]:
columns_to_keep = ['name','online_order','book_table','rate','location','approx_cost(for two people)']
data = data[columns_to_keep]
data.shape

(51717, 6)

# Renaming columns

In [10]:
columns_to_rename = []
for i in data.columns:
    columns_to_rename.append(i.capitalize())

columns_to_rename

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Location',
 'Approx_cost(for two people)']

# Dropping Duplicates

In [11]:
data.duplicated().value_counts()

True     32688
False    19029
Name: count, dtype: int64

In [12]:
data.drop_duplicates(inplace=True)

In [13]:
data.duplicated().value_counts()

False    19029
Name: count, dtype: int64

In [14]:
data.shape

(19029, 6)

# Cleaning Individual Columns

In [15]:
data.sample(15)

,name,online_order,book_table,rate,location,approx_cost(for two people)
40803,Uma's Home Food,No,No,3.6 /5,Marathahalli,300
43989,THE BEL ST.,No,No,3.9 /5,New BEL Road,"1,100"
5403,Naachiyar's,Yes,No,3.9/5,Ulsoor,600
5587,Ente Keralam,Yes,No,4.0/5,Ulsoor,"1,300"
9746,Donne Biriyani House,Yes,No,3.8/5,HSR,200
42172,Olive Bar And Kitchen,No,Yes,4.5 /5,Richmond Road,"1,800"
24004,Healthie,Yes,No,3.3/5,Hennur,600
49269,Chicken Man,Yes,No,3.7 /5,Bellandur,400
51530,A1 Hot Dum Biryani,No,No,3.2 /5,Whitefield,150
18402,Nandini Andhra Style Mess,No,No,3.5/5,Old Airport Road,350
40207,Sri Sai Dosa Center,No,No,NEW,Malleshwaram,100
39247,Imperial Room,No,No,3.2 /5,Majestic,"1,000"
13823,Dilli 6,No,No,3.2/5,Electronic City,450
50180,Abhiruchi Restaurant,Yes,No,3.7 /5,Whitefield,550
21361,TAB - Take A Break,No,No,4.1 /5,JP Nagar,550

In [16]:
data.columns = columns_to_rename

In [17]:
data.sample(15)

,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
7466,Rayalaseema Spices,Yes,No,3.5/5,Brookefield,550
40085,Big Mishra Pedha,No,No,NaN,Rajajinagar,250
30645,The Night King,No,No,3.3 /5,Koramangala 7th Block,400
8646,Ahmed's Little Hut,Yes,No,NaN,BTM,250
27679,Fruit Juice Bar,No,No,NaN,Koramangala 6th Block,300
2484,MG's Fine Dining & Bar - Springs Hotel & Spa,No,Yes,3.8/5,Basavanagudi,800
40280,Starbucks,No,No,4.3 /5,Sadashiv Nagar,700
18051,Green G Juice Bar,Yes,No,3.5/5,Indiranagar,200
6873,Banana Leaf,Yes,No,2.9/5,Marathahalli,600
1661,KHANAPUR TIFFINS,No,No,NaN,South Bangalore,250
3431,Brahmin Tiffins & Coffee,No,No,-,Basavanagudi,100
49032,Shree Khana Khazana,Yes,No,4.1 /5,Bellandur,450
20059,SGS Non Veg - Gundu Pulav,Yes,No,3.6/5,Jayanagar,400
7404,Little Nature,Yes,No,3.1/5,Marathahalli,250
39577,Kool Joint,Yes,No,3.4 /5,Basaveshwara Nagar,200

In [18]:
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0)
data["Book_table"] = data["Book_table"].apply(lambda x: 1 if x == "Yes" else 0)

data.head(5)

,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
0,Jalsa,1,1,4.1/5,Banashankari,800
1,Spice Elephant,1,0,4.1/5,Banashankari,800
2,San Churro Cafe,1,0,3.8/5,Banashankari,800
3,Addhuri Udupi Bhojana,0,0,3.7/5,Banashankari,300
4,Grand Village,0,0,3.8/5,Basavanagudi,600

In [19]:
data["Rate"].unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',    'NEW',  '2.9/5',  '3.5/5',      nan,  '2.6/5', '3.8 /5',
  '3.4/5',  '4.5/5',  '2.5/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',
  '2.3/5', '3.4 /5',      '-', '3.6 /5',  '4.8/5', '3.9 /5', '4.2 /5',
 '4.0 /5', '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
 '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5', '4.3 /5',
 '4.4 /5',  '4.9/5',  '2.1/5',  '2.0/5',  '1.8/5', '4.6 /5', '4.9 /5',
 '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5',
 '2.0 /5', '1.8 /5']
Length: 65, dtype: str

In [20]:
data["Rate"] = data["Rate"].replace(["NEW", "-"], np.nan)

In [21]:
data["Rate"].unique()

<StringArray>
[ '4.1/5',  '3.8/5',  '3.7/5',  '3.6/5',  '4.6/5',  '4.0/5',  '4.2/5',
  '3.9/5',  '3.1/5',  '3.0/5',  '3.2/5',  '3.3/5',  '2.8/5',  '4.4/5',
  '4.3/5',      nan,  '2.9/5',  '3.5/5',  '2.6/5', '3.8 /5',  '3.4/5',
  '4.5/5',  '2.5/5',  '2.7/5',  '4.7/5',  '2.4/5',  '2.2/5',  '2.3/5',
 '3.4 /5', '3.6 /5',  '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5',
 '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5', '3.5 /5', '2.7 /5',
 '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5', '4.3 /5', '4.4 /5',  '4.9/5',
  '2.1/5',  '2.0/5',  '1.8/5', '4.6 /5', '4.9 /5', '3.0 /5', '4.8 /5',
 '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5']
Length: 63, dtype: str

In [22]:
data["Location"].unique()

<StringArray>
[                 'Banashankari',                  'Basavanagudi',
                   'Mysore Road',                     'Jayanagar',
            'Kumaraswamy Layout',          'Rajarajeshwari Nagar',
                   'Vijay Nagar',                   'Uttarahalli',
                      'JP Nagar',               'South Bangalore',
                   'City Market',                    'Nagarbhavi',
             'Bannerghatta Road',                           'BTM',
               'Kanakapura Road',                  'Bommanahalli',
                             nan,                'CV Raman Nagar',
               'Electronic City',                           'HSR',
                  'Marathahalli',                 'Sarjapur Road',
                 'Wilson Garden',                  'Shanti Nagar',
         'Koramangala 5th Block',         'Koramangala 8th Block',
                 'Richmond Road',         'Koramangala 7th Block',
                     'Jalahalli',         'Koramangala 4th Block',
                     'Bellandur',                    'Whitefield',
                'East Bangalore',              'Old Airport Road',
                   'Indiranagar',         'Koramangala 1st Block',
                   'Frazer Town',                      'RT Nagar',
                       'MG Road',                  'Brigade Road',
                  'Lavelle Road',                 'Church Street',
                        'Ulsoor',                'Residency Road',
                  'Shivajinagar',                 'Infantry Road',
                'St. Marks Road',               'Cunningham Road',
              'Race Course Road',             'Commercial Street',
                 'Vasanth Nagar',                    'HBR Layout',
                        'Domlur',                       'Ejipura',
            'Jeevan Bhima Nagar',               'Old Madras Road',
                  'Malleshwaram',                 'Seshadripuram',
                  'Kammanahalli',         'Koramangala 6th Block',
                      'Majestic',                 'Langford Town',
             'Central Bangalore',                  'Sanjay Nagar',
                   'Brookefield',    'ITPL Main Road, Whitefield',
 'Varthur Main Road, Whitefield',                      'KR Puram',
         'Koramangala 2nd Block',         'Koramangala 3rd Block',
                   'Koramangala',                    'Hosur Road',
                   'Rajajinagar',                     'Banaswadi',
               'North Bangalore',                      'Nagawara',
                        'Hennur',                  'Kalyan Nagar',
                  'New BEL Road',                        'Jakkur',
               'Rammurthy Nagar',                  'Thippasandra',
                 'Kaggadasapura',                        'Hebbal',
                       'Kengeri',                   'Sankey Road',
                'Sadashiv Nagar',            'Basaveshwara Nagar',
                   'Yeshwantpur',                'West Bangalore',
                   'Magadi Road',                     'Yelahanka',
                'Sahakara Nagar',                        'Peenya']
Length: 94, dtype: str

In [23]:
data["Approx_cost(for two people)"].unique()

<StringArray>
[  '800',   '300',   '600',   '700',   '550',   '500',   '450',   '650',
   '400',   '900',   '200',   '750',   '150',   '850',   '100', '1,200',
   '350',   '250',   '950', '1,000', '1,500', '1,300',   '199',    '80',
 '1,100',   '160', '1,600',   '230',   '130',    '50',   '190', '1,700',
     nan, '1,400',   '180', '1,350', '2,200', '2,000', '1,800', '1,900',
   '330', '2,500', '2,100', '3,000', '2,800', '3,400',    '40', '1,250',
 '3,500', '4,000', '2,400', '2,600',   '120', '1,450',   '469',    '70',
 '3,200',    '60',   '560',   '240',   '360', '6,000', '1,050', '2,300',
 '4,100', '5,000', '3,700', '1,650', '2,700', '4,500',   '140']
Length: 71, dtype: str

In [29]:
data["Rate"] = data["Rate"].str.replace("/", " out of ")

In [30]:
data.sample(5)

,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
4137,Nutty Squirrel,1,0,3.8 out of 5,Bellandur,300
45006,Momo Time,1,0,NaN,Thippasandra,300
952,Kullad Cafe,1,0,3.9 out of 5,BTM,200
15831,The Wicked Cup,0,0,3.9 out of 5,HSR,350
44070,Firangi Bake,1,0,3.9 out of 5,Sahakara Nagar,600

In [31]:
data.reset_index()

,index,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
0,0,Jalsa,1,1,4.1 out of 5,Banashankari,800
1,1,Spice Elephant,1,0,4.1 out of 5,Banashankari,800
2,2,San Churro Cafe,1,0,3.8 out of 5,Banashankari,800
3,3,Addhuri Udupi Bhojana,0,0,3.7 out of 5,Banashankari,300
4,4,Grand Village,0,0,3.8 out of 5,Basavanagudi,600
...,...,...,...,...,...,...,...
19024,51631,Just Parathas,0,0,3.4 out of 5,Brookefield,250
19025,51632,SeeYa Restaurant,0,0,3.3 out of 5,KR Puram,350
19026,51641,Andhra Spices,0,0,3.2 out of 5,Brookefield,NaN
19027,51677,Bhagini,0,0,2.5 out of 5,Whitefield,800
19028,51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,0,NaN,Whitefield,"2,000"

In [ ]:
data.reset_index(drop=True, inplace=True)

In [36]:
data

,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
0,Jalsa,1,1,4.1 out of 5,Banashankari,800
1,Spice Elephant,1,0,4.1 out of 5,Banashankari,800
2,San Churro Cafe,1,0,3.8 out of 5,Banashankari,800
3,Addhuri Udupi Bhojana,0,0,3.7 out of 5,Banashankari,300
4,Grand Village,0,0,3.8 out of 5,Basavanagudi,600
...,...,...,...,...,...,...
19024,Just Parathas,0,0,3.4 out of 5,Brookefield,250
19025,SeeYa Restaurant,0,0,3.3 out of 5,KR Puram,350
19026,Andhra Spices,0,0,3.2 out of 5,Brookefield,NaN
19027,Bhagini,0,0,2.5 out of 5,Whitefield,800
19028,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,0,NaN,Whitefield,"2,000"

# Removing NaN value

In [37]:
data.isna().sum()

Name                              0
Online_order                      0
Book_table                        0
Rate                           3597
Location                         11
Approx_cost(for two people)     142
dtype: int64

In [41]:
data.shape

(19029, 6)

In [43]:
data.dropna(inplace = True)

In [45]:
data.shape

(15338, 6)

In [46]:
data.info()

<class 'pandas.DataFrame'>
Index: 15338 entries, 0 to 19027
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         15338 non-null  str
 1   Online_order                 15338 non-null  int64
 2   Book_table                   15338 non-null  int64
 3   Rate                         15338 non-null  str
 4   Location                     15338 non-null  str
 5   Approx_cost(for two people)  15338 non-null  str
dtypes: int64(2), str(4)
memory usage: 838.8 KB

In [55]:
data["Approx_cost(for two people)"] = data["Approx_cost(for two people)"].astype(str).str.replace(",","")
data["Approx_cost(for two people)"] = data["Approx_cost(for two people)"].astype(int)

In [56]:
data.sample(10)

,Name,Online_order,Book_table,Rate,Location,Approx_cost(for two people)
2936,Le Charcoal Xpress,1,0,3.5 out of 5,Sarjapur Road,500
895,Pizza Stop,1,0,3.9 out of 5,JP Nagar,600
11390,Paranthas and Dosas,0,0,3.7 out of 5,Kalyan Nagar,400
18874,Smaaash,0,1,4.0 out of 5,Whitefield,1500
1174,Willys Top Cafe,1,0,4.0 out of 5,Jayanagar,750
16454,Little Bites,0,0,3.8 out of 5,New BEL Road,400
17228,Chick Inn 24x7,0,0,3.6 out of 5,Malleshwaram,450
18820,Just Bake,1,0,3.8 out of 5,Whitefield,400
15728,Hashtag Kitchen,1,0,3.3 out of 5,Marathahalli,600
7972,Ziyan's Cafe 27th,0,1,4.0 out of 5,HSR,300

# Exporting to .csv and .xlsx

In [48]:
data.to_csv("Cleaned_Dataset.csv")

In [57]:
import openpyxl
print(f"openpyxl Version --> {openpyxl.__version__}")

openpyxl Version --> 3.1.5

In [58]:
data.to_excel("Zomato_Dataset.xlsx")