# Importing Packages

In [20]:
import pandas as pd
import numpy as np

print(f"NumPy Version --> {np.__version__}")
print(f"Pandas Version --> {pd.__version__}")

NumPy Version --> 1.26.4
Pandas Version --> 2.3.3

# Reading the .csv file

In [21]:
data = pd.read_csv("zomato.csv")

In [22]:
data.head(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [23]:
data.shape

(51717, 17)

In [24]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

# Delete Redundant Columns

In [26]:
columns_to_drop = ['url', 'address', 'votes','phone', 'rest_type', 'reviews_list', 'menu_item']
data.drop(columns = columns_to_drop,inplace = True)

In [27]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'location', 'dish_liked',
       'cuisines', 'approx_cost(for two people)', 'listed_in(type)',
       'listed_in(city)'],
      dtype='object')

# Renaming Columns

In [28]:
renamed_cols = []
for i in data.columns:
    renamed_cols.append(i.capitalize())
renamed_cols

['Name',
 'Online_order',
 'Book_table',
 'Rate',
 'Location',
 'Dish_liked',
 'Cuisines',
 'Approx_cost(for two people)',
 'Listed_in(type)',
 'Listed_in(city)']

In [29]:
data.columns = renamed_cols
data.columns

Index(['Name', 'Online_order', 'Book_table', 'Rate', 'Location', 'Dish_liked',
       'Cuisines', 'Approx_cost(for two people)', 'Listed_in(type)',
       'Listed_in(city)'],
      dtype='object')

# Dropping Duplicates

In [32]:
data.duplicated().value_counts()

False    51603
True       114
Name: count, dtype: int64

In [33]:
data.drop_duplicates(inplace=True)

In [34]:
data.duplicated().value_counts()

False    51603
Name: count, dtype: int64

In [35]:
data.shape

(51603, 10)

# Cleaning Individual Columns

In [36]:
data.sample(15)

,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
50394,The Deli - The Den Bengaluru,Yes,No,3.7 /5,"ITPL Main Road, Whitefield",NaN,"Bakery, Desserts",600,Delivery,Whitefield
3102,Sai Super Sandwich,Yes,No,NEW,Banashankari,NaN,"Sandwich, Beverages",200,Delivery,Basavanagudi
35983,Happy Brew,No,Yes,4.0 /5,Koramangala 5th Block,"Beer, Jalapeno Cheeseballs, Peri Peri Chicken ...","Continental, American, Chinese, BBQ, Salad","1,000",Delivery,Koramangala 7th Block
6299,VT Sindhur Veg,No,No,3.3/5,Richmond Road,NaN,"North Indian, Chinese",600,Dine-out,Brigade Road
21384,Roti Wala,Yes,No,4.2 /5,BTM,"Gulab Jamun, Buttermilk, Egg Bhurji, Sprout Sa...",North Indian,300,Dine-out,Jayanagar
39073,Sri Venkateshwara Vishnu Bhavan,No,No,NaN,Shanti Nagar,NaN,"South Indian, North Indian, Chinese",300,Dine-out,Lavelle Road
36593,Smoke - The Sizzler House,Yes,Yes,4.0 /5,Koramangala 7th Block,"Butter Garlic Prawns, Mocktails, Noodles, Sala...","Continental, Chinese, Thai, Italian, BBQ, Steak","1,100",Dine-out,Koramangala 7th Block
42500,Zaks Mediterranean Cuisine,Yes,No,3.9 /5,Frazer Town,"Biryani, Shawarma, Kunafa, Pita Bread, Fattous...","Mediterranean, Arabian, Lebanese",700,Delivery,MG Road
44612,Baba's Food Center,No,No,NaN,New BEL Road,NaN,"North Indian, Chinese",200,Dine-out,New BEL Road
44563,Goli Vada Pav No. 1,Yes,No,3.7 /5,New BEL Road,NaN,Street Food,200,Dine-out,New BEL Road
38340,Tasty Treats,No,No,NaN,MG Road,NaN,"South Indian, Chinese, Fast Food",350,Delivery,Lavelle Road
18874,Leon Grill,Yes,No,4.2/5,Indiranagar,"Burgers, Chocolate Mousse, Peri Peri Wings, Pe...","Burger, Turkish, Arabian, Fast Food, Salad, He...",500,Dine-out,Indiranagar
19498,XO Belgian Waffle,Yes,No,4.5/5,BTM,"Blueberry Waffles, Nutella Waffle, Hot Chocola...","Desserts, Beverages",400,Delivery,Jayanagar
11136,Tawa Sagara,Yes,No,3.8/5,Jayanagar,"Sea Food, Biryani, Fish Thali, Neer Dosa, Murg...","Mangalorean, Seafood",700,Dine-out,BTM
20623,Shri Vinayaka Ice N Juice,Yes,No,3.7/5,Jayanagar,NaN,"Fast Food, Beverages",200,Delivery,Jayanagar

In [37]:
data["Online_order"] = data["Online_order"].apply(lambda x: 1 if x == "Yes" else 0)
data["Book_table"] = data["Book_table"].apply(lambda x: 1 if x == "Yes" else 0)

data.head(5)

,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
0,Jalsa,1,1,4.1/5,Banashankari,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,1,0,4.1/5,Banashankari,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,1,0,3.8/5,Banashankari,"Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,0,0,3.7/5,Banashankari,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,0,0,3.8/5,Basavanagudi,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [38]:
data["Rate"].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [42]:
data["Rate"] = data["Rate"].replace(["NEW", "-"], np.nan)

In [40]:
data["Rate"].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', nan, '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [43]:
data["Location"].unique()

array(['Banashankari', 'Basavanagudi', 'Mysore Road', 'Jayanagar',
       'Kumaraswamy Layout', 'Rajarajeshwari Nagar', 'Vijay Nagar',
       'Uttarahalli', 'JP Nagar', 'South Bangalore', 'City Market',
       'Nagarbhavi', 'Bannerghatta Road', 'BTM', 'Kanakapura Road',
       'Bommanahalli', nan, 'CV Raman Nagar', 'Electronic City', 'HSR',
       'Marathahalli', 'Sarjapur Road', 'Wilson Garden', 'Shanti Nagar',
       'Koramangala 5th Block', 'Koramangala 8th Block', 'Richmond Road',
       'Koramangala 7th Block', 'Jalahalli', 'Koramangala 4th Block',
       'Bellandur', 'Whitefield', 'East Bangalore', 'Old Airport Road',
       'Indiranagar', 'Koramangala 1st Block', 'Frazer Town', 'RT Nagar',
       'MG Road', 'Brigade Road', 'Lavelle Road', 'Church Street',
       'Ulsoor', 'Residency Road', 'Shivajinagar', 'Infantry Road',
       'St. Marks Road', 'Cunningham Road', 'Race Course Road',
       'Commercial Street', 'Vasanth Nagar', 'HBR Layout', 'Domlur',
       'Ejipura', 'Jeevan Bhima Nagar', 'Old Madras Road', 'Malleshwaram',
       'Seshadripuram', 'Kammanahalli', 'Koramangala 6th Block',
       'Majestic', 'Langford Town', 'Central Bangalore', 'Sanjay Nagar',
       'Brookefield', 'ITPL Main Road, Whitefield',
       'Varthur Main Road, Whitefield', 'KR Puram',
       'Koramangala 2nd Block', 'Koramangala 3rd Block', 'Koramangala',
       'Hosur Road', 'Rajajinagar', 'Banaswadi', 'North Bangalore',
       'Nagawara', 'Hennur', 'Kalyan Nagar', 'New BEL Road', 'Jakkur',
       'Rammurthy Nagar', 'Thippasandra', 'Kaggadasapura', 'Hebbal',
       'Kengeri', 'Sankey Road', 'Sadashiv Nagar', 'Basaveshwara Nagar',
       'Yeshwantpur', 'West Bangalore', 'Magadi Road', 'Yelahanka',
       'Sahakara Nagar', 'Peenya'], dtype=object)

In [44]:
data["Approx_cost(for two people)"].unique()

array(['800', '300', '600', '700', '550', '500', '450', '650', '400',
       '900', '200', '750', '150', '850', '100', '1,200', '350', '250',
       '950', '1,000', '1,500', '1,300', '199', '80', '1,100', '160',
       '1,600', '230', '130', '50', '190', '1,700', nan, '1,400', '180',
       '1,350', '2,200', '2,000', '1,800', '1,900', '330', '2,500',
       '2,100', '3,000', '2,800', '3,400', '40', '1,250', '3,500',
       '4,000', '2,400', '2,600', '120', '1,450', '469', '70', '3,200',
       '60', '560', '240', '360', '6,000', '1,050', '2,300', '4,100',
       '5,000', '3,700', '1,650', '2,700', '4,500', '140'], dtype=object)

In [45]:
data["Rate"] = data["Rate"].str.replace("/", " out of ")

In [46]:
data.sample(5)

,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
24434,Moghul's Restaurant,1,0,3.0 out of 5,HBR Layout,NaN,"Mughlai, North Indian, Chinese",700,Delivery,Kalyan Nagar
3361,Cool Corner,0,0,4.2 out of 5,Basavanagudi,"Sandwich, Masala Dosa, Set Dosa, Onion Dosa, C...","Street Food, Fast Food",250,Dine-out,Basavanagudi
36902,Fetchpod Cafe,0,0,2.9 out of 5,Koramangala 6th Block,NaN,"Cafe, North Indian, Chinese, Continental",500,Dine-out,Koramangala 7th Block
14833,Fullyfilled,1,0,4.0 out of 5,Indiranagar,"Momos, Shawarma, Chicken Shawarama","Sandwich, Fast Food, Momos",200,Delivery,Frazer Town
11986,Croons,0,0,3.8 out of 5,Brigade Road,NaN,Desserts,350,Delivery,Church Street

In [47]:
data.reset_index()

,index,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
0,0,Jalsa,1,1,4.1 out of 5,Banashankari,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,1,Spice Elephant,1,0,4.1 out of 5,Banashankari,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,2,San Churro Cafe,1,0,3.8 out of 5,Banashankari,"Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,3,Addhuri Udupi Bhojana,0,0,3.7 out of 5,Banashankari,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,4,Grand Village,0,0,3.8 out of 5,Basavanagudi,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...
51598,51712,Best Brews - Four Points by Sheraton Bengaluru...,0,0,3.6 out of 5,Whitefield,NaN,Continental,"1,500",Pubs and bars,Whitefield
51599,51713,Vinod Bar And Restaurant,0,0,NaN,Whitefield,NaN,Finger Food,600,Pubs and bars,Whitefield
51600,51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,0,NaN,Whitefield,NaN,Finger Food,"2,000",Pubs and bars,Whitefield
51601,51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,1,4.3 out of 5,"ITPL Main Road, Whitefield","Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield
51602,51716,The Nest - The Den Bengaluru,0,0,3.4 out of 5,"ITPL Main Road, Whitefield",NaN,"Finger Food, North Indian, Continental","1,500",Pubs and bars,Whitefield

In [48]:
data.reset_index(drop=True, inplace=True)

In [49]:
data

,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
0,Jalsa,1,1,4.1 out of 5,Banashankari,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,1,0,4.1 out of 5,Banashankari,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,1,0,3.8 out of 5,Banashankari,"Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,0,0,3.7 out of 5,Banashankari,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,0,0,3.8 out of 5,Basavanagudi,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...
51598,Best Brews - Four Points by Sheraton Bengaluru...,0,0,3.6 out of 5,Whitefield,NaN,Continental,"1,500",Pubs and bars,Whitefield
51599,Vinod Bar And Restaurant,0,0,NaN,Whitefield,NaN,Finger Food,600,Pubs and bars,Whitefield
51600,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,0,NaN,Whitefield,NaN,Finger Food,"2,000",Pubs and bars,Whitefield
51601,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,1,4.3 out of 5,"ITPL Main Road, Whitefield","Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield
51602,The Nest - The Den Bengaluru,0,0,3.4 out of 5,"ITPL Main Road, Whitefield",NaN,"Finger Food, North Indian, Continental","1,500",Pubs and bars,Whitefield

# Removing NaN value

In [50]:
data.isna().sum()

Name                               0
Online_order                       0
Book_table                         0
Rate                           10019
Location                          21
Dish_liked                     28008
Cuisines                          45
Approx_cost(for two people)      344
Listed_in(type)                    0
Listed_in(city)                    0
dtype: int64

In [51]:
data.shape

(51603, 10)

In [52]:
data.dropna(inplace = True)

In [53]:
data.shape

(23286, 10)

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23286 entries, 0 to 51601
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name                         23286 non-null  object
 1   Online_order                 23286 non-null  int64
 2   Book_table                   23286 non-null  int64
 3   Rate                         23286 non-null  object
 4   Location                     23286 non-null  object
 5   Dish_liked                   23286 non-null  object
 6   Cuisines                     23286 non-null  object
 7   Approx_cost(for two people)  23286 non-null  object
 8   Listed_in(type)              23286 non-null  object
 9   Listed_in(city)              23286 non-null  object
dtypes: int64(2), object(8)
memory usage: 2.0+ MB

In [56]:
data["Approx_cost(for two people)"] = data["Approx_cost(for two people)"].astype(str).str.replace(",","")
data["Approx_cost(for two people)"] = data["Approx_cost(for two people)"].astype(int)

In [57]:
data.sample(10)

,Name,Online_order,Book_table,Rate,Location,Dish_liked,Cuisines,Approx_cost(for two people),Listed_in(type),Listed_in(city)
46793,South Spicy Bites,1,0,3.7 out of 5,Basaveshwara Nagar,"Fish, Tandoori Chicken, Neer Dosa, Sea Food","North Indian, Chinese",500,Dine-out,Rajajinagar
6178,Peppa Zzing,1,0,4.3 out of 5,Infantry Road,"Burgers, Pasta, Cheesy Fries, Beef Burger, Ice...","Cafe, Fast Food, Burger",800,Dine-out,Brigade Road
8817,Birinz,1,0,4.2 out of 5,HSR,"Gulab Jamun, Chicken Guntur, Mushroom Biryani,...","Biryani, Kebab, Fast Food",400,Delivery,BTM
48787,Blue Berry Restaurant,1,0,3.9 out of 5,Bellandur,"Tandoori Chicken, Coffee, Butter Chicken, Fish...","North Indian, Biryani, Chinese, Beverages",650,Delivery,Sarjapur Road
21850,Kabab Magic,1,0,4.0 out of 5,Jayanagar,"Chicken Grill, Grape Juice, Biryani, Shawarma ...","North Indian, Kebab, Fast Food",500,Delivery,JP Nagar
5152,The Mughal's,1,0,3.7 out of 5,Frazer Town,"Chicken Biryani, Lemon Chicken Roll","Mughlai, North Indian, Chinese",400,Delivery,Brigade Road
47950,Hammered,1,1,4.6 out of 5,Cunningham Road,"Sangria, Chicken Satay, Crispy Corn, Masala Fr...","North Indian, Thai, Japanese, Continental, Cafe",1300,Desserts,Residency Road
37540,Fill N Chill Resto Bar & Pub,1,1,3.9 out of 5,Koramangala 4th Block,"Beer, Biryani, Cocktails, Masala Peanuts, Chic...","Finger Food, North Indian, Chinese",1200,Pubs and bars,Koramangala 7th Block
23015,Corner House Ice Cream,1,0,4.4 out of 5,Jayanagar,"Hot Chocolate Fudge, Chocolate Malt, Thick Sha...","Ice Cream, Desserts",400,Desserts,JP Nagar
10840,Koramangala Social,1,0,4.6 out of 5,Koramangala 7th Block,"Manchow Soup, Caramel Custard, Cocktails, Bbq ...","American, North Indian, Chinese, Finger Food",1500,Dine-out,BTM

# Exporting to .csv and .xlsx

In [58]:
data.to_csv("Cleaned_Dataset.csv")