# Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd

print(f"NumPy Version --> {np.__version__}")
print(f"Pandas Version --> {pd.__version__}")

NumPy Version --> 2.4.6
Pandas Version --> 3.0.3

# Importing sales.csv

In [2]:
data = pd.read_csv("../raw dataset/sales.csv")
data.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

# Inspecting the Dataset before proceeding to clean it

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [4]:
data.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

# Working on Column: Transaction ID

In [5]:
data["Transaction ID"]

0       TXN_1961373
1       TXN_4977031
2       TXN_4271903
3       TXN_7034554
4       TXN_3160411
           ...
9995    TXN_7672686
9996    TXN_9659401
9997    TXN_5255387
9998    TXN_7695629
9999    TXN_6170729
Name: Transaction ID, Length: 10000, dtype: str

In [6]:
data["Transaction ID"] = data["Transaction ID"].astype(str).str.replace("TXN_","")

In [7]:
data["Transaction ID"]

0       1961373
1       4977031
2       4271903
3       7034554
4       3160411
         ...
9995    7672686
9996    9659401
9997    5255387
9998    7695629
9999    6170729
Name: Transaction ID, Length: 10000, dtype: str

In [8]:
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

# Dealing with inconsistent data and/or NaN values

In [9]:
data.duplicated().value_counts()

False    10000
Name: count, dtype: int64

In [10]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [11]:
data.shape

(10000, 8)

In [12]:
data.dropna().shape

(4550, 8)

In [13]:
data.dropna(inplace = True)
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9984,3142496,Smoothie,UNKNOWN,4.0,4.0,Cash,Takeaway,2023-07-27
9986,2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9992,2739140,Smoothie,4,4.0,16.0,UNKNOWN,In-store,2023-07-05
9999,6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [15]:
data["Quantity"].unique()

<StringArray>
['2', '4', '3', '5', 'ERROR', '1', 'UNKNOWN']
Length: 7, dtype: str

In [17]:
data["Transaction Date"].unique()

<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-10-06', '2023-10-28', '2023-11-07',      'ERROR', '2023-05-03',
 ...
 '2023-11-11', '2023-05-20', '2023-08-08', '2023-01-23', '2023-02-14',
 '2023-11-14', '2023-05-22', '2023-09-24', '2023-05-25', '2023-05-13']
Length: 367, dtype: str

# Removing values such as "UNKNOWN", "ERROR"

In [23]:
data[~data.isin(["UNKNOWN","ERROR"]).any(axis = 1)]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
4,3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
10,2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07
12,7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03
...,...,...,...,...,...,...,...,...
9975,9668108,Cake,1,3.0,3.0,Cash,In-store,2023-01-20
9979,9933628,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-20
9986,2858441,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-12-14
9991,3897619,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-02-24
9999,6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [25]:
data[~data.isin(["UNKNOWN","ERROR"]).any(axis = 1)]["Quantity"].unique()

<StringArray>
['2', '4', '5', '3', '1']
Length: 5, dtype: str

In [26]:
data = data[~data.isin(["UNKNOWN","ERROR"]).any(axis = 1)]

In [27]:
data.sample(15)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6152,9514996,Sandwich,2,4.0,8.0,Credit Card,Takeaway,2023-07-25
6354,7981162,Cake,3,3.0,9.0,Credit Card,Takeaway,2023-05-30
9510,6612143,Tea,5,1.5,7.5,Cash,In-store,2023-11-07
8162,7416196,Smoothie,2,4.0,8.0,Cash,In-store,2023-10-20
4005,8305936,Juice,3,3.0,9.0,Digital Wallet,In-store,2023-08-02
34,8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
7692,5858713,Cookie,2,1.0,2.0,Credit Card,In-store,2023-03-05
6868,6670371,Tea,3,1.5,4.5,Credit Card,Takeaway,2023-05-01
5459,4385240,Cookie,4,1.0,4.0,Cash,Takeaway,2023-02-10
5785,6026451,Juice,2,3.0,6.0,Cash,In-store,2023-11-06
4552,5796131,Smoothie,3,4.0,12.0,Digital Wallet,Takeaway,2023-09-30
5008,8838566,Cake,5,3.0,15.0,Digital Wallet,In-store,2023-07-25
1669,4075432,Sandwich,5,4.0,20.0,Cash,In-store,2023-09-12
3700,4407959,Tea,1,1.5,1.5,Digital Wallet,Takeaway,2023-01-28
8608,2369294,Sandwich,2,4.0,8.0,Cash,Takeaway,2023-09-07

In [31]:
data.shape

(3089, 8)

# Verifying if all UNKNOWN and ERROR values are removed

In [35]:
(data == "UNKNOWN").sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [36]:
(data == "ERROR").sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

# Inspecting more of the dataset

In [37]:
data.sample(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
6898,2437725,Sandwich,4,4.0,16.0,Credit Card,Takeaway,2023-01-27
5592,2919225,Coffee,4,2.0,8.0,Credit Card,Takeaway,2023-02-14
8897,5129701,Smoothie,2,4.0,8.0,Credit Card,Takeaway,2023-11-09
4848,1278539,Tea,1,1.5,1.5,Credit Card,Takeaway,2023-04-04
6937,1088497,Sandwich,1,4.0,4.0,Digital Wallet,Takeaway,2023-07-05
3867,6063689,Cookie,3,1.0,3.0,Cash,In-store,2023-02-01
8615,7221126,Tea,5,1.5,7.5,Digital Wallet,In-store,2023-10-11
2195,6629689,Sandwich,2,4.0,8.0,Credit Card,In-store,2023-05-29
3488,4209748,Cookie,2,1.0,2.0,Digital Wallet,Takeaway,2023-10-24
6463,9388222,Cookie,1,1.0,1.0,Digital Wallet,In-store,2023-04-21

In [43]:
data.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [52]:
cols = ["Price Per Unit","Total Spent"]
for col in cols:
    data[col] = data[col].astype(float)

data["Quantity"] = data["Quantity"].astype(int)

In [53]:
data.dtypes

Transaction ID          str
Item                    str
Quantity              int64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
dtype: object

In [73]:
data["Transaction Date"] = pd.to_datetime(data["Transaction Date"])
data["Transaction ID"] = data["Transaction ID"].astype(int)

In [74]:
data.dtypes

Transaction ID               int64
Item                           str
Quantity                     int64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [75]:
data.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1581562,Coffee,2,2.0,4.0,Cash,In-store,2023-01-01
1,2024598,Sandwich,1,4.0,4.0,Digital Wallet,In-store,2023-01-01
2,2104473,Cake,3,3.0,9.0,Digital Wallet,Takeaway,2023-01-01
3,2192787,Sandwich,5,4.0,20.0,Cash,In-store,2023-01-01
4,9161256,Smoothie,2,4.0,8.0,Digital Wallet,In-store,2023-01-01
5,7367474,Juice,5,3.0,15.0,Digital Wallet,Takeaway,2023-01-01
6,3093284,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-01-01
7,8308672,Salad,2,5.0,10.0,Digital Wallet,Takeaway,2023-01-01
8,4801947,Juice,1,3.0,3.0,Digital Wallet,Takeaway,2023-01-01
9,5563675,Tea,3,1.5,4.5,Digital Wallet,In-store,2023-01-01

In [62]:
data = data.sort_values("Transaction Date").reset_index(drop = True)

In [76]:
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,1581562,Coffee,2,2.0,4.0,Cash,In-store,2023-01-01
1,2024598,Sandwich,1,4.0,4.0,Digital Wallet,In-store,2023-01-01
2,2104473,Cake,3,3.0,9.0,Digital Wallet,Takeaway,2023-01-01
3,2192787,Sandwich,5,4.0,20.0,Cash,In-store,2023-01-01
4,9161256,Smoothie,2,4.0,8.0,Digital Wallet,In-store,2023-01-01
...,...,...,...,...,...,...,...,...
3084,6541110,Cookie,3,1.0,3.0,Cash,In-store,2023-12-30
3085,4592205,Cookie,3,1.0,3.0,Credit Card,In-store,2023-12-30
3086,7108012,Tea,1,1.5,1.5,Digital Wallet,Takeaway,2023-12-31
3087,1714348,Sandwich,2,4.0,8.0,Cash,Takeaway,2023-12-31
3088,1389258,Salad,1,5.0,5.0,Cash,Takeaway,2023-12-31

# Exporting the cleaned dataset into a .csv

In [77]:
data.to_csv("Cleaned_Dataset.csv")

# Exporting the cleaned dataset into a .xlsx

In [66]:
import openpyxl
print(f"openpyxl Version --> {openpyxl.__version__}")

openpyxl Version --> 3.1.5

In [86]:
data.to_excel("Cleaned_Dataset.xlsx")

from openpyxl import load_workbook

workbook = load_workbook("Cleaned_Dataset.xlsx")
sheet = workbook.active

for column_cells in sheet.columns:
    column_letter = column_cells[0].column_letter
    max_length = 0

    for cell in column_cells:
        value = cell.value
        if hasattr(value, "strftime"):
            text = value.strftime("%Y-%m-%d %H:%M:%S")
        else:
            text = "" if value is None else str(value)
        max_length = max(max_length, len(text))

    sheet.column_dimensions[column_letter].width = max_length + 2

workbook.save("Cleaned_Dataset.xlsx")

In [87]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3089 entries, 0 to 3088
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    3089 non-null   int64
 1   Item              3089 non-null   str
 2   Quantity          3089 non-null   int64
 3   Price Per Unit    3089 non-null   float64
 4   Total Spent       3089 non-null   float64
 5   Payment Method    3089 non-null   str
 6   Location          3089 non-null   str
 7   Transaction Date  3089 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(3)
memory usage: 193.2 KB